### ISSUE TITLE
non-Linux portability request

### ISSUE THREAD

**Issue by 0-wiz-0** [googleprojectzero/halfempty#12]
halfempty does not compile on NetBSD. I fixed some issues in https://github.com/googleprojectzero/halfempty/pull/11 but two more remain:

* the use of `splice()`, which is Linux-specific
* the use of `sendfile()`, which I think FreeBSD also supports, but NetBSD doesn't.

Could you please advise on workarounds for these?
Thanks.

**Comment by taviso** [comment]
Neat, I think just adding `EXTRA = sendfile_generic.o splice_generic.o` to the Makefile might work, there's a minimal generic implementation in there. If that works, happy to add it!

**Comment by 0-wiz-0** [comment]
Thanks, that does indeed work! I've added the patch to my pull request #11.
