### ISSUE TITLE
Suggestion: additional topics

### ISSUE THREAD

**Issue by pwaller** [googleprojectzero/halfempty#4]
Nice project!

I discovered this some months ago and then forgot about it.

Despite knowing it existed, I struggled a bit to find it, searching for "testcase reduction" and "parallel". I used Google, Duckduckgo and GitHub search. I had "parallel creduce" in mind, which wasn't quite right. I didn't think of the word "minimization" until later.

Could I suggest putting more topics on the GitHub repository might make it easier to find? e.g.

* testcase-minimization
* testcase-reduction

**Comment by taviso** [comment]
Done, thanks for the suggestion!
