### ISSUE TITLE
Error when compiling in Ubuntu 16.04  - /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments

### ISSUE THREAD

**Issue by thatmichael85** [googleprojectzero/halfempty#7]
Hi Tavis,

I tried compiling in Ubuntu 16.04, but can't really figure out how to fix it at the moment.
This is the error I get:
Checking for glib-2.0...ok
gcc -Wall -std=gnu99 -O2 -ggdb3 -march=native -fPIC -Wno-format-zero-length -Wno-unused-parameter -UNDEBUG -UG_DISABLE_ASSERT `getconf LFS_CFLAGS` `pkg-config --cflags glib-2.0` -D_GNU_SOURCE  -c -o halfempty.o halfempty.c
gcc -Wall -std=gnu99 -O2 -ggdb3 -march=native -fPIC -Wno-format-zero-length -Wno-unused-parameter -UNDEBUG -UG_DISABLE_ASSERT `getconf LFS_CFLAGS` `pkg-config --cflags glib-2.0` -D_GNU_SOURCE  -c -o proc.o proc.c
gcc -Wall -std=gnu99 -O2 -ggdb3 -march=native -fPIC -Wno-format-zero-length -Wno-unused-parameter -UNDEBUG -UG_DISABLE_ASSERT `getconf LFS_CFLAGS` `pkg-config --cflags glib-2.0` -D_GNU_SOURCE  -c -o bisect.o bisect.c
hexdump -ve '"" 1/1 "%#02x" ","' monitor.tpl > monitor.h
gcc -Wall -std=gnu99 -O2 -ggdb3 -march=native -fPIC -Wno-format-zero-length -Wno-unused-parameter -UNDEBUG -UG_DISABLE_ASSERT `getconf LFS_CFLAGS` `pkg-config --cflags glib-2.0` -D_GNU_SOURCE  -c -o util.o util.c
In file included from /usr/include/fcntl.h:289,
                 from util.c:34:
In function 'open',
    inlined from 'g_unlinked_tmp' at util.c:154:17:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ^~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'util.o' failed
make: *** [util.o] Error 1

Thank you.

**Comment by thatmichael85** [comment]
Update:

I kinda did a workaround by adding permissions.
From util.c:
   154     gint   fd = open("/tmp", O_TMPFILE | O_RDWR);
To:
   154     gint   fd = open("/tmp", O_TMPFILE | O_RDWR, **0755**);

**Comment by taviso** [comment]
Thank you for the bug report! I don't know why I don't get that error when compiling, but I think you're right that's a real bug, I'll fix it right now.
