### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Pl0414141** [googleprojectzero/halfempty#9]
Hi!

do you have any plan to support Windows applications?

**Comment by taviso** [comment]
It already works under WSL, and can run and monitor Windows programs - I've used it to minimize Windows bugs like this, and I try to make sure new releases are tested under WSL.

I think in most cases this works quite well!

**Comment by Pl0414141** [comment]
Awesome!, an example with windbg it would also be great too!

**Comment by taviso** [comment]
Good idea, I wrote a small example here:

https://github.com/googleprojectzero/halfempty/wiki/Windows

Please let me know if you have any suggestions, or if you run into any problems - happy to improve the docs or fix any bugs!

**Comment by Pl0414141** [comment]
Taviso,

Correct me if I'm wrong but, in the process of reducing bytes in the file, your tool could find additional crashes unintentionally, perhaps it would be preferable to detect crashes in a more generic way instead of error code 'Access violation - code c0000005'?

**Comment by taviso** [comment]
You're right, I wanted to keep the example simple, I guess a solution would be using cdb script to verify the crash site:

```
.if (@rip == target!foo+123) { .printf "__crashed__\n" }
```
And then grepping the log for `__crashed__`, let me know if you have a better solution!
